language: python
python:
    - "3.5"
install:
    - "pip install pygame"
    - "pip install pep8"
    - "pip install coveralls"
    - "pip install codeclimate-test-reporter"
script:
  - pep8 --show-source --show-pep8 *.py */*.py */**/*.py
  - cd tests
  - pytest
  - py.test --cov=YourModuleYouWantToCover test_folder
  - codeclimate-test-reporter --file .coverage
after-sucess:
  - coverage
  - coverage report
  - coveralls
  - codeclimate-test-reporter
notifications:
  slack: fgatactics:iT20GMXMrn2a7JXka0oVboqR
