language: python
python:
    - "3.5"
install:
    - "pip install pygame"
    - "pip install pep8"
    - "pip install coveralls"
    - "pip install pylint"
script:
  - pep8 --show-source --show-pep8 *.py */*.py */**/*.py
  - cd tests
  - pytest
  - nosetests --with-coverage --cover-erase --cover-inclusive --cover-package=pylint_server
after-sucess:
  - coverage
  - coverage report
  - coveralls
  - pylint --output-format=html pylint_server > /tmp/pylint-report.html
notifications:
  slack: fgatactics:iT20GMXMrn2a7JXka0oVboqR
